# Generated by Django 5.2.7 on 2025-12-01 15:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('activ', 'Activ'), ('inactiv', 'Inactiv')], default='activ', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('culoare', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('furnizor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('locatie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
                ('nr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('organizator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nr_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('vip', models.BooleanField(default=False)),
                ('adresa', models.CharField(blank=True, max_length=200, null=True)),
                ('tara', models.CharField(blank=True, max_length=20, null=True)),
                ('cod', models.CharField(blank=True, max_length=100, null=True)),
                ('email_confirmat', models.BooleanField(default=False)),
                ('blocat', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('produs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_app.categorie')),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_app.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventar',
            fields=[
                ('inventar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantitate', models.PositiveIntegerField(default=0)),
                ('modif', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('date_modif', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscari_stoc', to='magazin_app.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('benefit', models.CharField(max_length=200)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country_from', models.CharField(max_length=100)),
                ('produse', models.ManyToManyField(related_name='ingrediente', to='magazin_app.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('comanda_id', models.AutoField(primary_key=True, serialize=False)),
                ('valoare', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tip_ambalaj', models.CharField(choices=[('cutie', 'Cutie'), ('plic', 'Plic'), ('palet', 'Palet')], max_length=20)),
                ('curier', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produse', models.ManyToManyField(related_name='comenzi', to='magazin_app.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('promotie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('produse', models.ManyToManyField(related_name='promotii', to='magazin_app.produs')),
            ],
        ),
        migrations.CreateModel(
            name='PromotieNoua',
            fields=[
                ('id_promotie', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateField(auto_now_add=True)),
                ('data_expirare', models.DateField()),
                ('reducere', models.IntegerField(default=10)),
                ('descriere', models.TextField()),
                ('categorii', models.ManyToManyField(to='magazin_app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='PuncteFidelitate',
            fields=[
                ('id_puncte', models.AutoField(primary_key=True, serialize=False)),
                ('data_comenzii', models.DateField()),
                ('data_revendicarii', models.DateField(blank=True, null=True)),
                ('multiplicator', models.DecimalField(decimal_places=1, max_digits=3)),
                ('puncte_castigate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=20)),
                ('mesaj', models.CharField(max_length=300)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_app.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id_viz', models.AutoField(primary_key=True, serialize=False)),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin_app.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
